sonar.projectKey=prompthub-web
sonar.projectName=PromptHub Web

sonar.sources=app,server
sonar.tests=app,server
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/.nuxt/**,**/.output/**,**/coverage/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
