sonar.projectKey=prompthub-api
sonar.projectName=PromptHub API

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
